### PR TITLE
updates based on code review with Jessie

### PR DESCRIPTION
**Pull request by lmcglohon**
@jkeck Had to put the use of passing object into ckey method because I need to be able to pull the current druid's ckey along with it's collection ckey (if it has a collection)

Also, couldn't get the try to work so put back in the complicated code for identityMetadata

I think setting up a method that memoizes content and identity metadata is a great idea.  Will work on that next.

Sorry about the weird spacing differences.  I guess that is from using difference editors?  Weird, huh?

### CODE REVIEW

**Comment by jkeck** [comment]
Hmm, interesting, where is the ckey method being used to get the collection's ckey?  I only see two references to this method in the codebase and in both instances it appears that it's always dealing with the item the class was instantiated with (perhaps there is something else going on that I'm not aware of).  Perhaps there should be a separate method for getting the collection ckey? (I may be being naive about how these robots are called and work).

https://github.com/sul-dlss/item-release/blob/fdff30bdc77afab37687217b5313be6dc02506b0/lib/dor/update_marc_record_service.rb#L18
https://github.com/sul-dlss/item-release/blob/86bc7560fa45d7df757002ea234a7e76d6062153/robots/release/update_marc.rb#L22

**Comment by lmcglohon** [comment]
It's buried here:

https://github.com/sul-dlss/item-release/blob/fdff30bdc77afab37687217b5313be6dc02506b0/lib/dor/update_marc_record_service.rb#L176

~Laney

**Comment by jkeck** [comment]
Ah, okay.  Well, I think we have two paths to clean this up then (the last of which is probably the more correct way to do so).

1. If this is a method that really does not require anything about the the instance of the class, then maybe this should be a class method (so `self.ckey(object)`).  Then you can just call that method on the class (`UpdateMarcRecordService.ckey(object)` or `self.class.ckey(object)`).
2. Alternatively, this logic honestly probably belongs in their respective `Dor::Item` datastream classes.  There are other pieces of the infrastructure that will most likely require this information as well and not duplicating how to get the ckey of an object in different robots would probably be better.  If that was the case then your class doesn't have to have any knowledge about how to get a ckey from an object and all you have to do is ask for it for the item or for the collection.  (the same can potentially be said about a few of the other methods as well such as `barcode`, `object_type`, `display_type`, etc.)

**Comment by aeschylus** [comment]
Noticed a comment about spacing. Editorconfig is one way to manage that
between contributors.

http://editorconfig.org
On Thursday, 20 August 2015, Jessie Keck <notifications@github.com> wrote:

> Ah, okay. Well, I think we have two paths to clean this up then (the last
> of which is probably the more correct way to do so).
>
>    1. If this is a method that really does not require anything about the
>    the instance of the class, then maybe this should be a class method (so
>    self.ckey(object)). Then you can just call that method on the class (
>    UpdateMarcRecordService.ckey(object) or self.class.ckey(object)).
>    2. Alternatively, this logic honestly probably belongs in their
>    respective Dor::Item datastream classes. There are other pieces of the
>    infrastructure that will most likely require this information as well and
>    not duplicating how to get the ckey of an object in different robots would
>    probably be better. If that was the case then your class doesn't have to
>    have any knowledge about how to get a ckey from an object and all you have
>    to do is ask for it for the item or for the collection. (the same can
>    potentially be said about a few of the other methods as well such as
>    barcode, object_type, display_type, etc.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sul-dlss/item-release/pull/24#issuecomment-133136195>.
>


-- 
*Drew Winget*
Visualisation Engineer
Digital Library Systems and Services
Stanford, CA 94305
(972) 740-7974

**Comment by lmcglohon** [comment]
Good to know!

**Pull request merged**
