### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by peetucket** [comment]
it looks like bluepill got downgraded - was this expected?

**Comment by cbeer** [comment]
It looks like `bluepill` got downgraded because they pinned to `activesupport` `< 5`. I guess I'll go take a look upstream.

**Comment by cbeer** [comment]
https://github.com/bluepill-rb/bluepill/pull/46, although dependencies and rubocop have drifted since their last passing build..

**Comment by drh-stanford** [comment]
bluepill needs be >= 0.0.70 due to a bug in 0.0.69 -- see https://github.com/bluepill-rb/bluepill/issues/27

**Comment by drh-stanford** [comment]
For ^^^ robot-controller should probably pin bluepill to `>= 0.0.70` -- i'll look into that some more...

**Comment by drh-stanford** [comment]
The bluepill fix for Rails 5 support was fixed in 0.1.2+ but they haven't released a new version. I added a pin to bluepill's github `master` for now

**Pull request merged**
