### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by cbeer** [comment]
@lmcglohon when running the tests before or after this change, I'm seeing a couple test failures. Would you mind taking a look?

**Comment by lmcglohon** [comment]
@cbeer  I'm looking into this.

**Comment by cbeer** [comment]
@lmcglohon bump?

**Comment by lmcglohon** [comment]
@cbeer Hope to get to this today (7/2)

**Pull request merged**
